FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -yq tzdata build-essential

RUN ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

WORKDIR /app

COPY backend/requirements.txt requirements.txt
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

COPY backend .

EXPOSE 7777

CMD tail -f /dev/null

# ENTRYPOINT ["bash", "docker_entrypoint.sh"]