services:
  core:
    build:
      dockerfile: Dockerfile
    image: wiseflow:latest
    # set following as you need
    # environment:
      # - TZ=Asia/Shanghai
      # - LANG=zh_CN.UTF-8
      # - LC_ALL=zh_CN.UTF-8
    tty: true
    stdin_open: true
    entrypoint: bash ./core/docker_entrypoint.sh
    env_file:
      - .env
    ports:
      - 8090:8090
      - 8077:8077
    volumes:
      - ./${PROJECT_DIR}/pb_data:/app/pb/pb_data
      - ./${PROJECT_DIR}:/app/${PROJECT_DIR}
