version: '3.8'

services:
  # WiseFlow 主应用
  wiseflow:
    build:
      context: .
      dockerfile: Dockerfile.multiplatform
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: wiseflow-app
    environment:
      # 从环境文件加载配置
      - ENV_FILE=/app/.env
      # 数据库配置
      - POCKETBASE_URL=http://pocketbase:8090
    volumes:
      # 配置文件
      - ./.env:/home/wiseflow/.env:ro
      # 数据持久化
      - wiseflow_data:/home/wiseflow/data
      - wiseflow_logs:/home/wiseflow/logs
    depends_on:
      - pocketbase
    networks:
      - wiseflow-network
    restart: unless-stopped
    
  # PocketBase 数据库
  pocketbase:
    image: spectado/pocketbase:latest
    container_name: wiseflow-db
    ports:
      - "8090:8090"
    volumes:
      # 数据库数据持久化
      - pocketbase_data:/pb_data
      # 数据库迁移文件
      - ./pb/pb_migrations:/pb_migrations:ro
    environment:
      - PB_ENCRYPTION_KEY=${PB_ENCRYPTION_KEY:-your-encryption-key-here}
    networks:
      - wiseflow-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Web 管理界面 (可选)
  admin:
    image: nginx:alpine
    container_name: wiseflow-admin
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - pocketbase
    networks:
      - wiseflow-network
    restart: unless-stopped

  # 代理服务器 (可选)
  proxy:
    image: nginx:alpine
    container_name: wiseflow-proxy
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - ./proxy.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
    networks:
      - wiseflow-network
    restart: unless-stopped

volumes:
  # 应用数据卷
  wiseflow_data:
    driver: local
  wiseflow_logs:
    driver: local
  # 数据库数据卷  
  pocketbase_data:
    driver: local

networks:
  wiseflow-network:
    driver: bridge