#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
DB="$ROOT/db/published_track.db"

mkdir -p "$ROOT/db"

sqlite3 "$DB" <<'SQL'

-- 微信公众号
CREATE TABLE IF NOT EXISTS pub_wx_mp (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  content_type TEXT NOT NULL CHECK(content_type IN ('article','video','post')),
  source_folder TEXT NOT NULL,
  publish_url TEXT,
  publish_date TEXT NOT NULL,
  distribute_status INTEGER NOT NULL DEFAULT 0,
  reads INTEGER DEFAULT 0,
  shares INTEGER DEFAULT 0,
  favorites INTEGER DEFAULT 0,
  likes INTEGER DEFAULT 0,
  comments INTEGER DEFAULT 0,
  top_comment TEXT,
  notes TEXT,
  cal_enabled INTEGER DEFAULT 0,
  cal_score_er INTEGER,
  cal_score_hp INTEGER,
  cal_score_sr INTEGER,
  cal_score_ql INTEGER,
  cal_score_na INTEGER,
  cal_score_ab INTEGER,
  cal_score_pv INTEGER,
  cal_composite REAL,
  cal_rubric_version TEXT,
  cal_scored_at TEXT,
  created_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime')),
  updated_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime'))
);

-- 知乎
CREATE TABLE IF NOT EXISTS pub_zhihu (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  content_type TEXT NOT NULL CHECK(content_type IN ('article','video','post')),
  source_folder TEXT NOT NULL,
  publish_url TEXT,
  publish_date TEXT NOT NULL,
  distribute_status INTEGER NOT NULL DEFAULT 0,
  views INTEGER DEFAULT 0,
  upvotes INTEGER DEFAULT 0,
  comments INTEGER DEFAULT 0,
  favorites INTEGER DEFAULT 0,
  top_comment TEXT,
  notes TEXT,
  cal_enabled INTEGER DEFAULT 0,
  cal_score_er INTEGER,
  cal_score_hp INTEGER,
  cal_score_sr INTEGER,
  cal_score_ql INTEGER,
  cal_score_na INTEGER,
  cal_score_ab INTEGER,
  cal_score_pv INTEGER,
  cal_composite REAL,
  cal_rubric_version TEXT,
  cal_scored_at TEXT,
  created_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime')),
  updated_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime'))
);

-- B站
CREATE TABLE IF NOT EXISTS pub_bilibili (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  content_type TEXT NOT NULL CHECK(content_type IN ('article','video','post')),
  source_folder TEXT NOT NULL,
  publish_url TEXT,
  publish_date TEXT NOT NULL,
  distribute_status INTEGER NOT NULL DEFAULT 0,
  plays INTEGER DEFAULT 0,
  danmaku INTEGER DEFAULT 0,
  likes INTEGER DEFAULT 0,
  coins INTEGER DEFAULT 0,
  favorites INTEGER DEFAULT 0,
  shares INTEGER DEFAULT 0,
  comments INTEGER DEFAULT 0,
  top_comment TEXT,
  notes TEXT,
  cal_enabled INTEGER DEFAULT 0,
  cal_score_er INTEGER,
  cal_score_hp INTEGER,
  cal_score_sr INTEGER,
  cal_score_ql INTEGER,
  cal_score_na INTEGER,
  cal_score_ab INTEGER,
  cal_score_pv INTEGER,
  cal_composite REAL,
  cal_rubric_version TEXT,
  cal_scored_at TEXT,
  created_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime')),
  updated_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime'))
);

-- 抖音
CREATE TABLE IF NOT EXISTS pub_douyin (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  content_type TEXT NOT NULL CHECK(content_type IN ('article','video','post')),
  source_folder TEXT NOT NULL,
  publish_url TEXT,
  publish_date TEXT NOT NULL,
  distribute_status INTEGER NOT NULL DEFAULT 0,
  plays INTEGER DEFAULT 0,
  likes INTEGER DEFAULT 0,
  comments INTEGER DEFAULT 0,
  shares INTEGER DEFAULT 0,
  favorites INTEGER DEFAULT 0,
  top_comment TEXT,
  notes TEXT,
  cal_enabled INTEGER DEFAULT 0,
  cal_score_er INTEGER,
  cal_score_hp INTEGER,
  cal_score_sr INTEGER,
  cal_score_ql INTEGER,
  cal_score_na INTEGER,
  cal_score_ab INTEGER,
  cal_score_pv INTEGER,
  cal_composite REAL,
  cal_rubric_version TEXT,
  cal_scored_at TEXT,
  created_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime')),
  updated_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime'))
);

-- 快手
CREATE TABLE IF NOT EXISTS pub_kuaishou (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  content_type TEXT NOT NULL CHECK(content_type IN ('article','video','post')),
  source_folder TEXT NOT NULL,
  publish_url TEXT,
  publish_date TEXT NOT NULL,
  distribute_status INTEGER NOT NULL DEFAULT 0,
  plays INTEGER DEFAULT 0,
  likes INTEGER DEFAULT 0,
  comments INTEGER DEFAULT 0,
  shares INTEGER DEFAULT 0,
  top_comment TEXT,
  notes TEXT,
  cal_enabled INTEGER DEFAULT 0,
  cal_score_er INTEGER,
  cal_score_hp INTEGER,
  cal_score_sr INTEGER,
  cal_score_ql INTEGER,
  cal_score_na INTEGER,
  cal_score_ab INTEGER,
  cal_score_pv INTEGER,
  cal_composite REAL,
  cal_rubric_version TEXT,
  cal_scored_at TEXT,
  created_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime')),
  updated_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime'))
);

-- 小红书
CREATE TABLE IF NOT EXISTS pub_xhs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  content_type TEXT NOT NULL CHECK(content_type IN ('article','video','post')),
  source_folder TEXT NOT NULL,
  publish_url TEXT,
  publish_date TEXT NOT NULL,
  distribute_status INTEGER NOT NULL DEFAULT 0,
  views INTEGER DEFAULT 0,
  likes INTEGER DEFAULT 0,
  favorites INTEGER DEFAULT 0,
  comments INTEGER DEFAULT 0,
  shares INTEGER DEFAULT 0,
  top_comment TEXT,
  notes TEXT,
  cal_enabled INTEGER DEFAULT 0,
  cal_score_er INTEGER,
  cal_score_hp INTEGER,
  cal_score_sr INTEGER,
  cal_score_ql INTEGER,
  cal_score_na INTEGER,
  cal_score_ab INTEGER,
  cal_score_pv INTEGER,
  cal_composite REAL,
  cal_rubric_version TEXT,
  cal_scored_at TEXT,
  created_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime')),
  updated_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime'))
);

-- 今日头条
CREATE TABLE IF NOT EXISTS pub_toutiao (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  content_type TEXT NOT NULL CHECK(content_type IN ('article','video','post')),
  source_folder TEXT NOT NULL,
  publish_url TEXT,
  publish_date TEXT NOT NULL,
  distribute_status INTEGER NOT NULL DEFAULT 0,
  impressions INTEGER DEFAULT 0,
  reads INTEGER DEFAULT 0,
  comments INTEGER DEFAULT 0,
  likes INTEGER DEFAULT 0,
  top_comment TEXT,
  notes TEXT,
  cal_enabled INTEGER DEFAULT 0,
  cal_score_er INTEGER,
  cal_score_hp INTEGER,
  cal_score_sr INTEGER,
  cal_score_ql INTEGER,
  cal_score_na INTEGER,
  cal_score_ab INTEGER,
  cal_score_pv INTEGER,
  cal_composite REAL,
  cal_rubric_version TEXT,
  cal_scored_at TEXT,
  created_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime')),
  updated_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime'))
);

-- 掘金
CREATE TABLE IF NOT EXISTS pub_juejin (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  content_type TEXT NOT NULL CHECK(content_type IN ('article','video','post')),
  source_folder TEXT NOT NULL,
  publish_url TEXT,
  publish_date TEXT NOT NULL,
  distribute_status INTEGER NOT NULL DEFAULT 0,
  views INTEGER DEFAULT 0,
  likes INTEGER DEFAULT 0,
  comments INTEGER DEFAULT 0,
  favorites INTEGER DEFAULT 0,
  top_comment TEXT,
  notes TEXT,
  cal_enabled INTEGER DEFAULT 0,
  cal_score_er INTEGER,
  cal_score_hp INTEGER,
  cal_score_sr INTEGER,
  cal_score_ql INTEGER,
  cal_score_na INTEGER,
  cal_score_ab INTEGER,
  cal_score_pv INTEGER,
  cal_composite REAL,
  cal_rubric_version TEXT,
  cal_scored_at TEXT,
  created_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime')),
  updated_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime'))
);

-- Twitter/X
CREATE TABLE IF NOT EXISTS pub_twitter (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  content_type TEXT NOT NULL CHECK(content_type IN ('article','video','post')),
  source_folder TEXT NOT NULL,
  publish_url TEXT,
  publish_date TEXT NOT NULL,
  distribute_status INTEGER NOT NULL DEFAULT 0,
  views INTEGER DEFAULT 0,
  likes INTEGER DEFAULT 0,
  retweets INTEGER DEFAULT 0,
  replies INTEGER DEFAULT 0,
  bookmarks INTEGER DEFAULT 0,
  notes TEXT,
  cal_enabled INTEGER DEFAULT 0,
  cal_score_er INTEGER,
  cal_score_hp INTEGER,
  cal_score_sr INTEGER,
  cal_score_ql INTEGER,
  cal_score_na INTEGER,
  cal_score_ab INTEGER,
  cal_score_pv INTEGER,
  cal_composite REAL,
  cal_rubric_version TEXT,
  cal_scored_at TEXT,
  created_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime')),
  updated_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime'))
);

-- Facebook
CREATE TABLE IF NOT EXISTS pub_facebook (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  content_type TEXT NOT NULL CHECK(content_type IN ('article','video','post')),
  source_folder TEXT NOT NULL,
  publish_url TEXT,
  publish_date TEXT NOT NULL,
  distribute_status INTEGER NOT NULL DEFAULT 0,
  reach INTEGER DEFAULT 0,
  likes INTEGER DEFAULT 0,
  comments INTEGER DEFAULT 0,
  shares INTEGER DEFAULT 0,
  notes TEXT,
  cal_enabled INTEGER DEFAULT 0,
  cal_score_er INTEGER,
  cal_score_hp INTEGER,
  cal_score_sr INTEGER,
  cal_score_ql INTEGER,
  cal_score_na INTEGER,
  cal_score_ab INTEGER,
  cal_score_pv INTEGER,
  cal_composite REAL,
  cal_rubric_version TEXT,
  cal_scored_at TEXT,
  created_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime')),
  updated_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime'))
);

-- Instagram
CREATE TABLE IF NOT EXISTS pub_instagram (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  content_type TEXT NOT NULL CHECK(content_type IN ('article','video','post')),
  source_folder TEXT NOT NULL,
  publish_url TEXT,
  publish_date TEXT NOT NULL,
  distribute_status INTEGER NOT NULL DEFAULT 0,
  reach INTEGER DEFAULT 0,
  likes INTEGER DEFAULT 0,
  comments INTEGER DEFAULT 0,
  shares INTEGER DEFAULT 0,
  saves INTEGER DEFAULT 0,
  notes TEXT,
  cal_enabled INTEGER DEFAULT 0,
  cal_score_er INTEGER,
  cal_score_hp INTEGER,
  cal_score_sr INTEGER,
  cal_score_ql INTEGER,
  cal_score_na INTEGER,
  cal_score_ab INTEGER,
  cal_score_pv INTEGER,
  cal_composite REAL,
  cal_rubric_version TEXT,
  cal_scored_at TEXT,
  created_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime')),
  updated_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime'))
);

-- TikTok
CREATE TABLE IF NOT EXISTS pub_tiktok (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  content_type TEXT NOT NULL CHECK(content_type IN ('article','video','post')),
  source_folder TEXT NOT NULL,
  publish_url TEXT,
  publish_date TEXT NOT NULL,
  distribute_status INTEGER NOT NULL DEFAULT 0,
  plays INTEGER DEFAULT 0,
  likes INTEGER DEFAULT 0,
  comments INTEGER DEFAULT 0,
  shares INTEGER DEFAULT 0,
  favorites INTEGER DEFAULT 0,
  top_comment TEXT,
  notes TEXT,
  cal_enabled INTEGER DEFAULT 0,
  cal_score_er INTEGER,
  cal_score_hp INTEGER,
  cal_score_sr INTEGER,
  cal_score_ql INTEGER,
  cal_score_na INTEGER,
  cal_score_ab INTEGER,
  cal_score_pv INTEGER,
  cal_composite REAL,
  cal_rubric_version TEXT,
  cal_scored_at TEXT,
  created_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime')),
  updated_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime'))
);

-- YouTube
CREATE TABLE IF NOT EXISTS pub_youtube (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  content_type TEXT NOT NULL CHECK(content_type IN ('article','video','post')),
  source_folder TEXT NOT NULL,
  publish_url TEXT,
  publish_date TEXT NOT NULL,
  distribute_status INTEGER NOT NULL DEFAULT 0,
  views INTEGER DEFAULT 0,
  likes INTEGER DEFAULT 0,
  comments INTEGER DEFAULT 0,
  shares INTEGER DEFAULT 0,
  notes TEXT,
  cal_enabled INTEGER DEFAULT 0,
  cal_score_er INTEGER,
  cal_score_hp INTEGER,
  cal_score_sr INTEGER,
  cal_score_ql INTEGER,
  cal_score_na INTEGER,
  cal_score_ab INTEGER,
  cal_score_pv INTEGER,
  cal_composite REAL,
  cal_rubric_version TEXT,
  cal_scored_at TEXT,
  created_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime')),
  updated_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime'))
);

-- Pinterest
CREATE TABLE IF NOT EXISTS pub_pinterest (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  content_type TEXT NOT NULL CHECK(content_type IN ('article','video','post')),
  source_folder TEXT NOT NULL,
  publish_url TEXT,
  publish_date TEXT NOT NULL,
  distribute_status INTEGER NOT NULL DEFAULT 0,
  impressions INTEGER DEFAULT 0,
  saves INTEGER DEFAULT 0,
  comments INTEGER DEFAULT 0,
  notes TEXT,
  cal_enabled INTEGER DEFAULT 0,
  cal_score_er INTEGER,
  cal_score_hp INTEGER,
  cal_score_sr INTEGER,
  cal_score_ql INTEGER,
  cal_score_na INTEGER,
  cal_score_ab INTEGER,
  cal_score_pv INTEGER,
  cal_composite REAL,
  cal_rubric_version TEXT,
  cal_scored_at TEXT,
  created_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime')),
  updated_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime'))
);

-- Threads
CREATE TABLE IF NOT EXISTS pub_threads (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  content_type TEXT NOT NULL CHECK(content_type IN ('article','video','post')),
  source_folder TEXT NOT NULL,
  publish_url TEXT,
  publish_date TEXT NOT NULL,
  distribute_status INTEGER NOT NULL DEFAULT 0,
  views INTEGER DEFAULT 0,
  likes INTEGER DEFAULT 0,
  reposts INTEGER DEFAULT 0,
  replies INTEGER DEFAULT 0,
  notes TEXT,
  cal_enabled INTEGER DEFAULT 0,
  cal_score_er INTEGER,
  cal_score_hp INTEGER,
  cal_score_sr INTEGER,
  cal_score_ql INTEGER,
  cal_score_na INTEGER,
  cal_score_ab INTEGER,
  cal_score_pv INTEGER,
  cal_composite REAL,
  cal_rubric_version TEXT,
  cal_scored_at TEXT,
  created_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime')),
  updated_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime'))
);

-- 微信视频号
CREATE TABLE IF NOT EXISTS pub_wx_channel (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  content_type TEXT NOT NULL CHECK(content_type IN ('article','video','post')),
  source_folder TEXT NOT NULL,
  publish_url TEXT,
  publish_date TEXT NOT NULL,
  distribute_status INTEGER NOT NULL DEFAULT 0,
  plays INTEGER DEFAULT 0,
  likes INTEGER DEFAULT 0,
  comments INTEGER DEFAULT 0,
  shares INTEGER DEFAULT 0,
  favorites INTEGER DEFAULT 0,
  top_comment TEXT,
  notes TEXT,
  cal_enabled INTEGER DEFAULT 0,
  cal_score_er INTEGER,
  cal_score_hp INTEGER,
  cal_score_sr INTEGER,
  cal_score_ql INTEGER,
  cal_score_na INTEGER,
  cal_score_ab INTEGER,
  cal_score_pv INTEGER,
  cal_composite REAL,
  cal_rubric_version TEXT,
  cal_scored_at TEXT,
  created_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime')),
  updated_at TEXT DEFAULT (strftime('%Y-%m-%d %H:%M:%S','now','localtime'))
);

SQL

echo '{"ok":true,"message":"published_track.db initialized (with cal_ score columns)"}'
